### ISSUE TITLE
Strange behaviour 

### ISSUE THREAD

**Issue by kaykurokawa** [kaykurokawa/pyrader_frontend#44]
When I go to: http://blkdat.com/?price&symbol=BTC&unit=EUR&exchange=kraken&interval=hour

I get an error although the graph displays.
![screenshot from 2018-05-20 22-32-43](https://user-images.githubusercontent.com/7075051/40287791-d38d826c-5c7d-11e8-8ff8-db857bc13ca1.png)

And then, I cannot adjust the time interval on the graph, my mouse gets stuck to the slider.

**Comment by joeysk2012** [comment]
Looks like the bar chart was trying to link to a line graph. Fixed it.
